<refentry id="{@id}">
	<refnamediv>
		<refname>Configuration Class</refname>
		<refpurpose>Config Class Documentation</refpurpose>
	</refnamediv>
	<refsynopsisdiv>
		<author>
			Mitos Kalandiel
			<authorblurb>
				{@link mailto:mitos@joker-solutions.org mitos[at]joker-solutions.org}
			</authorblurb>
		</author>
	</refsynopsisdiv>
	{@toc}
	<refsect1 id="{@id intro}">
		<title>Introduction</title>
		<para>
			This class .... 
		</para>
	</refsect1>
	<refsect1 id="{@id whatis}">
		<title>What is the purpose and function of this class?</title>
		<para>
			The JAF ("Joker Application Framework") intends to be a full grown
			CMS including all components that are needed for such a system.
		</para>
	</refsect1>
</refentry>